development:
  adapter: postgresql
  encoding: unicode
  database: rails_graphql_test_project_development
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: rails_graphql_test_project_test
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: rails_graphql_test_project_production
  host: localhost
